#!/bin/bash

TERMINFO="$(athdir /mit/barnowl share)"/terminfo
export TERMINFO
eval $(env SHELL=/bin/bash $(athdir /mit/barnowl bin)/barnowl-perl-config)

if [ -n "$ATHENA_SESSION_TMPDIR" ]; then
    PAR_GLOBAL_TMPDIR=$ATHENA_SESSION_TMPDIR
    export PAR_GLOBAL_TMPDIR
fi
if [ -z "$BARNOWL_REAL" ]; then
    BARNOWL_REAL=barnowl.real
fi

case $BARNOWL_REAL in
    /*) BARNOWL_REAL_PATH="$BARNOWL_REAL" ;;
    *) BARNOWL_REAL_PATH="$(athdir /mit/barnowl bin)/$BARNOWL_REAL" ;;
esac

# Detect zephyr name if necessary
if [ ! -x "$BARNOWL_REAL_PATH" ]; then
    if test -x /sbin/ldconfig && /sbin/ldconfig -p | grep -qF "libzephyr.so.4"; then
        ZEPHYR_SONAME=zephyr4
    else
        ZEPHYR_SONAME=zephyr3
    fi
    BARNOWL_REAL_PATH="$BARNOWL_REAL_PATH.$ZEPHYR_SONAME"
fi

exec "$BARNOWL_REAL_PATH" "$@"
